#!/bin/bash
# ============================================================================
# INSTRUCCIONES DE DEBUGGING - MENÚ DINÁMICO
# ============================================================================

echo "🔍 INSTRUCCIONES PARA DEBUGGING DEL MENÚ"
echo "=========================================="
echo ""
echo "El backend está devolviendo correctamente las 5 aplicaciones."
echo "El problema está en el frontend (React)."
echo ""
echo "📋 PASOS PARA DIAGNOSTICAR:"
echo ""
echo "1. Abre el navegador en: http://localhost:3000"
echo ""
echo "2. Abre la Consola de Desarrollador:"
echo "   - Chrome/Edge: F12 o Ctrl+Shift+I"
echo "   - Firefox: F12 o Ctrl+Shift+K"
echo "   - Safari: Cmd+Option+I"
echo ""
echo "3. Ve a la pestaña 'Console'"
echo ""
echo "4. Haz login con:"
echo "   Usuario: admin"
echo "   Password: Admin123!"
echo ""
echo "5. Busca en la consola estos mensajes:"
echo "   📋 Resultado del menú: ..."
echo "   ✅ Menú cargado: [array con 5 elementos]"
echo "   🎯 Sidebar - menú recibido: [array]"
echo ""
echo "6. Si ves errores en rojo, cópialos"
echo ""
echo "7. Ve a la pestaña 'Network' (Red)"
echo "   - Filtra por 'menu'"
echo "   - Verifica que aparezca una llamada a: /api/menu"
echo "   - Haz clic en ella y ve la respuesta"
echo ""
echo "=========================================="
echo ""
echo "🔧 POSIBLES PROBLEMAS:"
echo ""
echo "A) Si NO ves la llamada a /api/menu:"
echo "   → El servicio no se está llamando"
echo "   → Problema: menuService no está importado o no se ejecuta"
echo ""
echo "B) Si ves la llamada pero con error 401:"
echo "   → Las cookies no se están enviando"
echo "   → Problema: configuración de CORS o cookies"
echo ""
echo "C) Si ves la llamada exitosa (200) con 5 items:"
echo "   → El menú se está cargando pero no se renderiza"
echo "   → Problema: estado de React o componente Sidebar"
echo ""
echo "D) Si ves '🎯 Sidebar - menú recibido: []' (vacío):"
echo "   → El menú no está llegando al componente"
echo "   → Problema: Context no está propagando el estado"
echo ""
echo "=========================================="
echo ""
echo "🛠️ SOLUCIÓN RÁPIDA - LIMPIAR CACHÉ:"
echo ""
echo "En el navegador (con la app abierta):"
echo "  1. Ctrl+Shift+Delete (Limpiar datos)"
echo "  2. Marca: Cookies y Caché"
echo "  3. Limpia"
echo "  4. O simplemente: Ctrl+F5 (hard refresh)"
echo ""
echo "=========================================="
echo ""
echo "📞 Si el problema persiste:"
echo "   → Copia los mensajes de la consola"
echo "   → Copia la respuesta de /api/menu desde Network"
echo "   → Compártelos para diagnóstico detallado"
echo ""
